apiVersion: apps/v1
kind: Deployment
metadata:
  name: greydns
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greydns
  template:
    metadata:
      labels:
        app: greydns
    spec:
      serviceAccountName: greydns-sa
      containers:
        - name: greydns
          image: ghcr.io/math280h/greydns/greydns:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: "500m"
              memory: "128Mi"
            requests:
              cpu: "250m"
              memory: "64Mi"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: greydns-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: greydns-cluster-role
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch", "create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: greydns-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: greydns-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: greydns-cluster-role
  apiGroup: rbac.authorization.k8s.io
